version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    ports: 
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=qwerty
    - POSTGRES_USER=postgres
    volumes:
     - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
    - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: chef.povar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: chef
    volumes:
    - pgadmin-data:/var/lib/pgadmin

volumes: 
  local_pgdata:
  pgadmin-data: